apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster1
  region: ap-southeast-1


nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      PublicKeyName: 'shalini123'
  - name: ng2
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      PublicKeyName: 'shalini123'
